<%@ Page Language="vb" MasterPageFile="~/admin/layout/layout.Master" AutoEventWireup="false" CodeBehind="kelola_admin.aspx.vb" Inherits="SIPPDPU_1._0._0.kelola_admin" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">  
</asp:Content>  
<asp:Content ID="kelola" ContentPlaceHolderID="body" runat="server">
    <main id="main" class="main">
        <div class="row">
        <div class="col-12">
            <div class="card">
            <div class="card-body">
                <br />
                <div class ="row">
                    <div class ="col-10">
                        <h5 class="card-title">Kelola Admin</h5>
                    </div>
                    <div class ="col-2">
                        <a href ="tambah_admin.aspx" class="btn btn-primary"><i class="bi bi-plus-square"></i>&nbsp;&nbsp;Tambah Data</a>
                    </div>
                </div>
              <asp:GridView id="tabel_admin" runat ="server" AutoGenerateColumns ="false" CssClass ="table" AutoGenerateEditButton ="true"
                  AutoGenerateDeleteButton ="true" DataKeyNames ="Id_admin">
                  <Columns>
                      <asp:BoundField DataField ="Id_admin" HeaderText ="No" />
                      <asp:BoundField DataField ="Email" HeaderText ="Email" />
                      <asp:BoundField DataField ="Password" HeaderText ="Password" />
                      <asp:BoundField DataField ="Username" HeaderText ="Username" />
                  </Columns>
              </asp:GridView>
                
            </div>
          </div>
        </div>
    </div>
    </main>
</asp:Content>
