<%@ Page Language="vb" MasterPageFile="~/admin/layout/layout.Master" AutoEventWireup="false" CodeBehind="perbaikan_jalan.aspx.vb" Inherits="SIPPDPU_1._0._0.perbaikan_jalan" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">  
</asp:Content>  
<asp:Content ID="perbaikan" ContentPlaceHolderID="body" runat="server">
    <main id="main" class="main">
        <div class="row">
        <div class="col-12">
            <div class="card">
            <div class="card-body">
                <br />
                <div class ="row">
                    <div class ="col-10">
                        <h5 class="card-title">Perbaikan Jalan</h5>
                    </div>
                    <div class ="col-2">
                        <a href ="tambah_jalan.aspx" class="btn btn-primary"><i class="bi bi-plus-square"></i>&nbsp;&nbsp;Tambah Data</a>
                    </div>
                </div>
                

              <asp:GridView id="tabel_jalan" runat ="server" AutoGenerateColumns ="false" CssClass ="table" AutoGenerateEditButton ="true"
                  AutoGenerateDeleteButton ="true" DataKeyNames ="Id_jalan">
                  <Columns>
                      <asp:BoundField DataField ="Id_jalan" HeaderText ="No" />
                      <asp:BoundField DataField ="Nama_jalan" HeaderText ="Nama Jalan" />
                      <asp:BoundField DataField ="Lokasi" HeaderText ="Lokasi" />
                      <asp:BoundField DataField ="Status" HeaderText ="Status" />
                  </Columns>
              </asp:GridView>
            </div>
          </div>
        </div>
    </div>
    </main>
</asp:Content>
