'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class tambah_jalan

    '''<summary>
    '''nama_jalan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nama_jalan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lokasi_jalan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lokasi_jalan As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''status_jalan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_jalan As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''foto_jalan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents foto_jalan As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btn_tambah_jalan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_tambah_jalan As Global.System.Web.UI.WebControls.Button
End Class
